# Generated by Django 5.1.1 on 2024-09-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
