# Generated by Django 5.1.1 on 2024-09-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_review_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
