# Generated by Django 5.1.1 on 2024-09-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image_url',
        ),
    ]
