# Generated by Django 5.1.1 on 2024-09-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_rename_image_product_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='image',
            new_name='image_url',
        ),
    ]
